### ISSUE TITLE
Import error on Python 3.6.8

### ISSUE THREAD

**Issue by tpritzker** [justinfx/pyRpc#6]
Version import under package init causes issues with python 3:

> Traceback (most recent call last):
  File "my_file.py", line 5, in <module>
    from pyRpc import PyRpc
  File "env/lib/python3.6/site-packages/pyRpc/__init__.py", line 48, in <module>
    from _version import __version__
ModuleNotFoundError: No module named '_version'

Changing __init__.py from:
`from _version import __version__`
To:
`from ._version import __version__`

Seems to resolve the issue.

**Comment by justinfx** [comment]
Strange that this never came up back when the project was update to py3 support. Do you want to submit this as a pull request and I will merge it? Thanks!

**Comment by tpritzker** [comment]
Sure, I'll build it from source first locally, then send a PR

**Comment by justinfx** [comment]
I realised that this was actually fixed via #4 and I never tagged v0.3.1 and pushed to pypi. That has just been done, so you should be able to install the latest release from pypi.

**Comment by tpritzker** [comment]
Thanks! sorry I didn't get to it yet...
I uninstalled, then installed from the tarball in pypi with pip cache
disabled, still occurs:

Python 3.6.8 (default, Aug 20 2019, 17:12:48)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyRpc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pyRpc/__init__.py", line 48,
in <module>
    from _version import __version__
ModuleNotFoundError: No module named '_version'

**Comment by justinfx** [comment]
Can you confirm if the latest fixes in master finally solve the issues for you?

**Comment by tpritzker** [comment]
Works! installed from master using python setup.py install

**Comment by justinfx** [comment]
Thanks for confirming. I have released 0.4.0
